apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: openfaas
    group: io.openfaas.k8s.management
  name:  openfaas-replica-view
  namespace: openfaas-fn
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: openfaas
    group: io.openfaas.k8s.management
  name: openfaas-replica-view-role-binding
  namespace: openfaas-fn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openfaas-replica-view-role
subjects:
  - kind: ServiceAccount
    name: openfaas-replica-view
    namespace: openfaas-fn
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: openfaas
    group: io.openfaas.k8s.management
  name: openfaas-replica-view-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - list
      - get
      - watch

