apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: openfaas
    group: io.openfaas.k8s.management
  name:  openfaas-deployment-manage
  namespace: openfaas-fn
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: openfaas
    group: io.openfaas.k8s.management
  name: openfaas-deployment-manage-role-binding
  namespace: openfaas-fn
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: openfaas-deployment-manage-role
subjects:
  - kind: ServiceAccount
    name: openfaas-deployment-manage
    namespace: openfaas-fn
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: openfaas
    group: io.openfaas.k8s.management
  name: openfaas-deployment-manage-role
rules:
  - apiGroups: [""]
    resources: ["configmaps","services"]
    verbs: ["get", "list", "watch", "create", "patch", "update", "delete"]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - update
      - patch
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - create
      - patch
      - update
      - delete

