version: 1.0
provider:
  name: openfaas
  gateway: http://localhost:8080

functions:
  publish-resources:
    lang: python3
    handler: ./functions/publish-resources
    image: docker.io/fjudith/publish-resources:openfaas
    constraints:
     - "node.platform.os == linux"
    annotations:
      com.openfaas.serviceaccount: openfaas-replica-view
      topic: cron-function
      # schedule: "*/30 * * * *"
      schedule: "0 21 * * *"
    environment:
      NATS_ADDRESS: nats://nats-cluster.nats-io:4222
      RESCALER_NAME: rescaler

  downscale-replicas:
    lang: python3
    handler: ./functions/downscale-replicas
    image: docker.io/fjudith/downscale-replicas:openfaas
    constraints:
     - "node.platform.os == linux"
    annotations:
      com.openfaas.serviceaccount: openfaas-replica-manage
      topic: "k8s.replicas"
    environment:
      NATS_ADDRESS: nats://nats-cluster.nats-io:4222

  update-ingress:
    lang: python3
    handler: ./functions/update-ingress
    image: docker.io/fjudith/update-ingress:openfaas
    constraints:
     - "node.platform.os == linux"
    annotations:
      com.openfaas.serviceaccount: openfaas-ingress-manage
      topic: "k8s.replicas"
    environment:
      NATS_ADDRESS: nats://nats-cluster.nats-io:4222
  
  deploy-rescaler:
    lang: python3
    handler: ./functions/deploy-rescaler
    image: docker.io/fjudith/deploy-rescaler:openfaas
    constraints:
     - "node.platform.os == linux"
    annotations:
      com.openfaas.serviceaccount: openfaas-deployment-manage
      topic: "k8s.ingresses"
    environment:
      OPENFAAS_GATEWAY_URL: http://gateway.openfaas.svc.cluster.local:8080

  rescale-replicas:
    lang: python3
    handler: ./functions/rescale-replicas
    image: docker.io/fjudith/rescale-replicas:openfaas
    constraints:
     - "node.platform.os == linux"
    annotations:
      com.openfaas.serviceaccount: openfaas-rescale-manage
    environment:
      RESCALER_NAME: rescaler
    constraints:
     - "node.platform.os == linux"