version: 1.0
provider:
  name: openfaas
  gateway: http://localhost:8080

functions:
  publish-resources:
    lang: python3
    handler: ./publish-resources
    image: docker.io/fjudith/publish-resources:openfaas
    annotations:
      com.openfaas.serviceaccount: replica-view
      topic: cron-function
      schedule: "*/1 * * * *"
    environment:
      NATS_ADDRESS: nats://nats-cluster.nats-io:4222

  downscale-replicas:
    lang: python3
    handler: ./downscale-replicas
    image: docker.io/fjudith/downscale-replicas:openfaas
    annotations:
      com.openfaas.serviceaccount: replica-manage
    environment:
      NATS_ADDRESS: nats://nats-cluster.nats-io:4222

  update-ingress:
    lang: python3
    handler: ./update-ingress
    image: docker.io/fjudith/update-ingress:openfaas
    annotations:
      com.openfaas.serviceaccount: ingress-manage
    environment:
      NATS_ADDRESS: nats://nats-cluster.nats-io:4222
  
  web-rescaler:
    lang: python3
    handler: ./web-rescaler
    annotations:
      com.openfaas.serviceaccount: replica-manage # TODO: dedicated RBAC
    image: docker.io/fjudith/web-rescaler:openfaas

  rescale-replicas:
    lang: python3
    handler: ./rescale-replicas
    image: docker.io/fjudith/rescale-replicas:openfaas
    annotations:
      com.openfaas.serviceaccount: replica-manage
    environment:
      NATS_ADDRESS: nats://nats-cluster.nats-io:4222