version: 1.0
provider:
  name: openfaas
  gateway: http://localhost:8080

functions:
  publish-resources:
    lang: python3
    handler: ./publish-resources
    image: docker.io/fjudith/publish-resources:openfaas
    constraints:
     - "node.platform.os == linux"
    annotations:
      com.openfaas.serviceaccount: openfaas-replica-view
      topic: cron-function
      schedule: "*/5 * * * *"
      # schedule: "0 * * * *"
    environment:
      NATS_ADDRESS: nats://nats-cluster.nats-io:4222
      RESCALER_NAME: rescaler

  downscale-replicas:
    lang: python3
    handler: ./downscale-replicas
    image: docker.io/fjudith/downscale-replicas:openfaas
    constraints:
     - "node.platform.os == linux"
    annotations:
      com.openfaas.serviceaccount: openfaas-replica-manage
      topic: "k8s_replicas"
    environment:
      NATS_ADDRESS: nats://nats-cluster.nats-io:4222

  update-ingress:
    lang: python3
    handler: ./update-ingress
    image: docker.io/fjudith/update-ingress:openfaas
    constraints:
     - "node.platform.os == linux"
    annotations:
      com.openfaas.serviceaccount: openfaas-ingress-manage
      topic: "k8s_replicas"
    environment:
      NATS_ADDRESS: nats://nats-cluster.nats-io:4222
  
  deploy-rescaler:
    lang: python3
    handler: ./deploy-rescaler
    image: docker.io/fjudith/deploy-rescaler:openfaas
    constraints:
     - "node.platform.os == linux"
    annotations:
      com.openfaas.serviceaccount: openfaas-deployment-manage
      topic: "k8s_ingresses"

  rescale-replicas:
    lang: python3
    handler: ./rescale-replicas
    image: docker.io/fjudith/rescale-replicas:openfaas
    constraints:
     - "node.platform.os == linux"
    annotations:
      com.openfaas.serviceaccount: openfaas-rescale-manage
    environment:
      RESCALER_NAME: "rescaler"
    constraints:
     - "node.platform.os == linux"