apiVersion: v1
kind: Service
metadata:
  name: nginx-deploy
  namespace: demo
  labels:
    app: nginx
    type: deployment
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx
    type: deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: demo
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        type: deployment
    spec:
      containers:
      - name: nginx
        image: nginx:1.7.9
        ports:
        - containerPort: 80
          name: web
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    certmanager.k8s.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  name: nginx-deploy
  namespace: demo
spec:
  rules:
  - host: demo-deploy.example.com
    http:
      paths:
      - backend:
          serviceName: nginx-deploy
          servicePort: 80
        path: /deployment
      - backend:
          serviceName: nginx-sts
          servicePort: 80
        path: /statefulset
  tls:
  - hosts:
    - demo-deploy.example.com
    secretName: ningx-deploy-prod-cert