apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: fission
    group: io.fission.k8s.management
  name:  fission-replica-manage
  namespace: fission-funtion
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: fission
    group: io.fission.k8s.management
  name: fission-replica-manage-role-binding
  namespace: fission-funtion
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fission-replica-manage-role
subjects:
  - kind: ServiceAccount
    name: fission-replica-manage
    namespace: fission-funtion
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: fission
    group: io.fission.k8s.management
  name: fission-replica-manage-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments/scale
      - statefulsets/scale
    verbs:
      - patch
      - update

