apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: fission
    group: io.fission.k8s.management
  name:  fission-ingress-manage
  namespace: fission-funtion
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: fission
    group: io.fission.k8s.management
  name: fission-ingress-manage-role-binding
  namespace: fission-funtion
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fission-ingress-manage-role
subjects:
  - kind: ServiceAccount
    name: fission-ingress-manage
    namespace: fission-funtion
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: fission
    group: io.fission.k8s.management
  name: fission-ingress-manage-role
rules:
  - apiGroups: [""]
    resources: ["namespaces","services"]
    verbs: ["get", "list", "watch"]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - update
      - patch
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
    verbs:
      - get
      - list
      - create
      - patch
      - update
      - delete

