apiVersion: nuclio.io/v1
kind: NuclioFunction
metadata:
  name: update-ingress
  namespace: nuclio
  labels:
    nuclio.io/project-name: nozzle
spec:
  handler: handler:handle
  runtime: python:3.6
  serviceAccount: nuclio-ingress-manage
  description: >
    List resources from namepsace containing the appropriate lablel
  build:
    image: library/update-ingress
    registry: harbor.testruction.cloud
    baseImage: python:3.6-alpine
    commands:
      - "apk add --update --no-cache ca-certificates"
      - "pip install -r /opt/nuclio/requirements.txt"
      #  - "pip install kubernetes==10.0.1"
      #  - "pip install asyncio-nats-client==0.9.2"
  
  
