include:
- functions/deploy-rescaler/*
kind: ArchiveUploadSpec
name: functions-deploy-rescaler-n1lk

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: deploy-rescaler-48400ebc-8c3c-436d-80ef-2edeb7aefa56
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: nozzle
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://functions-deploy-rescaler-n1lk
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-29T19:18:57.7315792Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: deploy-rescaler
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: nozzle
    namespace: default
  functionTimeout: 60
  package:
    functionName: handler.handle
    packageref:
      name: deploy-rescaler-48400ebc-8c3c-436d-80ef-2edeb7aefa56
      namespace: default
  resources: {}
  secrets: null
