include:
- functions/downscale-replicas/*
kind: ArchiveUploadSpec
name: functions-downscale-replicas-R6Pu

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: downscale-replicas-461026e2-0a08-432e-bbde-723b0aa46e4b
  namespace: default
spec:
  deployment:
    checksum: {}
  environment:
    name: nozzle
    namespace: default
  source:
    checksum: {}
    type: url
    url: archive://functions-downscale-replicas-R6Pu
status:
  buildstatus: pending
  lastUpdateTimestamp: "2020-04-29T16:30:55.5293825Z"

---
apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: downscale-replicas
  namespace: default
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  configmaps: null
  environment:
    name: nozzle
    namespace: default
  functionTimeout: 60
  package:
    functionName: handler.handle
    packageref:
      name: downscale-replicas-461026e2-0a08-432e-bbde-723b0aa46e4b
      namespace: default
  resources: {}
  secrets: null
