apiVersion: nuclio.io/v1
kind: NuclioFunction
metadata:
  name: rescale-replicas
  namespace: nuclio
  labels:
    nuclio.io/project-name: nozzle
spec:
  handler: handler:handle
  runtime: python:3.6
  serviceAccount: nuclio-rescale-manage
  env:
    - name: RESCALER_NAME
      value: rescaler
  description: >
    Restore the amount of Deployment and Statefulset replicas, update the ingress resources and destroy the rescaler
  build:
    image: library/rescale-replicas
    registry: harbor.testruction.cloud
    baseImage: python:3.6-alpine
    commands:
      - "apk add --update --no-cache ca-certificates"
      - "pip install kubernetes==10.0.1"
