apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: argo
    group: io.argo.k8s.management
  name:  argo-rescale-manage
  namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: argo
    group: io.argo.k8s.management
  name: argo-rescale-manage-role-binding
  namespace: argo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-rescale-manage-role
subjects:
  - kind: ServiceAccount
    name: argo-rescale-manage
    namespace: argo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: argo
    group: io.argo.k8s.management
  name: argo-rescale-manage-role
rules:
  - apiGroups: [""]
    resources: ["configmaps", "services"]
    verbs: ["list", "delete"]
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - list
      - patch
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments
      - statefulsets
    verbs:
      - list
      - patch
      - delete
  - apiGroups:
      - extensions
      - apps
    resources:
      - deployments/scale
      - statefulsets/scale
    verbs:
      - patch
