apiVersion: nuclio.io/v1
kind: NuclioFunction
metadata:
  name: publish-resources
  namespace: nuclio
  labels:
    nuclio.io/project-name: nozzle
spec:
  handler: handler:handle
  runtime: python:3.6
  serviceAccount: nuclio-replica-view
  env:
    - name: NATS_ADDRESS
      value: nats://nats-cluster.nats-io:4222
    - name: RESCALER_NAME
      value: rescaler
  description: >
    List deployment and statefulset resources from namepsaces containing the appropriate labels
  build:
    image: library/publish-resources
    registry: harbor.testruction.cloud
    baseImage: python:3.6-alpine
    commands:
      - "apk add --update --no-cache ca-certificates"
      - "pip install kubernetes==10.0.1"
      - "pip install asyncio-nats-client==0.9.2"
