name: Argo container images

on:
 push:
  paths:
    - '.github/workflows/argo_images.yaml'
    - 'argo/steps/deploy-rescaler/**'
    - 'argo/steps/downscale-replicas/**'
    - 'argo/steps/publish-resources/**'
    - 'argo/steps/rescale-replicas/**'
    - 'argo/steps/update-ingress/**'
  pull_request:
    paths:
    - '.github/workflows/argo_images.yaml'
    - 'argo/steps/deploy-rescaler/**'
    - 'argo/steps/downscale-replicas/**'
    - 'argo/steps/publish-resources/**'
    - 'argo/steps/rescale-replicas/**'
    - 'argo/steps/update-ingress/**'

env:
  REPO: "docker.io/fjudith"

jobs:
  image-build:
    name: '${{ matrix.image }} (Python: ${{ matrix.python }})'
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        image:
          - deploy-rescaler
          - downscale-replicas
          - publish-resources
          - rescale-replicas
          - update-ingress
        python:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Set ENV variables
        run: |
          echo SEMVER_MAJOR=$(cat VERSION | awk -F '.' '{print $1}') >> $GITHUB_ENV
          echo SEMVER_MINOR=$(cat VERSION | awk -F '.' '{print $1"."$2}') >> $GITHUB_ENV
          echo SEMVER_PATCH=$(cat VERSION | awk -F '.' '{print $1"."$2"."$3}') >> $GITHUB_ENV
          echo BUILD_DATE=$(date -u "+%Y-%m-%d %H:%M:%S.%s") >> $GITHUB_ENV
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: |
            ${{ env.REPO }}/${{ matrix.image }}:${{ env.SEMVER_MAJOR }}-argo-python${{ matrix.python }}
            ${{ env.REPO }}/${{ matrix.image }}:${{ env.SEMVER_MINOR }}-argo-python${{ matrix.python }}
            ${{ env.REPO }}/${{ matrix.image }}:${{ env.SEMVER_PATCH }}-argo-python${{ matrix.python }}
            ${{ env.REPO }}/${{ matrix.image }}:argo-python${{ matrix.python }}
          build-args: |
            VCS_REF=${{ github.ref }}
            VERSION=${{ env.SEMVER_PATCH }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            PYTHON_VERSION=${{ matrix.python }}
          context: argo/steps/${{ matrix.image }}/
          file: argo/steps/${{ matrix.image }}/Dockerfile
          platforms: linux/amd64
          push: true