name: OpenFaaS container images

on:
 push:
  paths:
    - '.github/workflows/openfaas_images.yaml'
    - 'openfaas/stack.yml'
  pull_request:
    paths:
    - '.github/workflows/openfaas_images.yaml'
    - 'openfaas/stack.yml'

env:
  REPO: "docker.io/fjudith"

jobs:
  image-build:
    name: '${{ matrix.image }} (Python: ${{ matrix.python }})'
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        image:
          - deploy-rescaler
          - downscale-replicas
          - publish-resources
          - rescale-replicas
          - update-ingress
        python:
          - 3.9
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Set ENV variables
        run: |
          echo SEMVER_MAJOR=$(cat VERSION | awk -F '.' '{print $1}') >> $GITHUB_ENV
          echo SEMVER_MINOR=$(cat VERSION | awk -F '.' '{print $1"."$2}') >> $GITHUB_ENV
          echo SEMVER_PATCH=$(cat VERSION | awk -F '.' '{print $1"."$2"."$3}') >> $GITHUB_ENV
          echo BUILD_DATE=$(date -u "+%Y-%m-%d %H:%M:%S.%s") >> $GITHUB_ENV
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - run: |
          cp -Rf openfaas/* .
      
      - name: Pull template
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: template store pull python3
      - name: Run shrinkwrap build
        uses: docker://openfaas/faas-cli:latest-root
        with:
          args: build -f stack.yml --shrinkwrap --build-option=dev

      - name: Build image
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          tags: ${{ env.REPO }}/${{ matrix.image }}:${{ env.SEMVER_MAJOR }}-openfaas-python${{ matrix.python }},${{ env.REPO }}/${{ matrix.image }}:${{ env.SEMVER_MINOR }}-openfaas-python${{ matrix.python }},${{ env.REPO }}/${{ matrix.image }}:${{ env.SEMVER_PATCH }}-openfaas-python${{ matrix.python }},${{ env.REPO }}/${{ matrix.image }}:openfaas-python${{ matrix.python }}
          build-args:
            VCS_REF=${{ github.ref }}
            VERSION=${{ env.SEMVER_PATCH }}
            BUILD_DATE=${{ env.BUILD_DATE }}
            PYTHON_VERSION=${{ matrix.python }}
            ADDITIONAL_PACKAGE=build-base gcc
          context: build/${{ matrix.image }}/
          file: build/${{ matrix.image }}/Dockerfile
          platforms: linux/amd64
          push: true
