name: OpenFaaS container images

on:
 push:
  paths:
    - '.github/workflows/openfaas_images.yaml'
    - 'openfaas/stack.yml'
  pull_request:
    paths:
    - '.github/workflows/openfaas_images.yaml'
    - 'openfaas/stack.yml'

env:
  REPO: "docker.io/fjudith"

jobs:
  image-build:
    name: 'Stack (Python: ${{ matrix.python }})'
    runs-on: ubuntu-20.04
    
    strategy:
      matrix:
        python:
          - 3.9
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        with:
          submodules: true
    
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: true

      - name: Set ENV variables
        run: |
          echo SEMVER_MAJOR=$(cat VERSION | awk -F '.' '{print $1}') >> $GITHUB_ENV
          echo SEMVER_MINOR=$(cat VERSION | awk -F '.' '{print $1"."$2}') >> $GITHUB_ENV
          echo SEMVER_PATCH=$(cat VERSION | awk -F '.' '{print $1"."$2"."$3}') >> $GITHUB_ENV
          echo BUILD_DATE=$(date -u "+%Y-%m-%d %H:%M:%S.%s") >> $GITHUB_ENV
      
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}


      - name: Build images using OpenFaaS client
        working-directory: openfaas/
        run: |
          curl -sLO https://github.com/openfaas/faas-cli/releases/download/0.13.9/faas-cli && \
          curl -sLO https://github.com/openfaas/faas-cli/releases/download/0.13.9/faas-cli.sha256 && \
          sha256sum --check faas-cli.sha256 && \
          chmod +x ./faas-cli && sudo mv ./faas-cli /usr/local/bin/ && \
          faas-cli build -f ./stack.yml -o dev && \
          faas-cli push -f ./stack.yml
